expenses/urls.py
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import path, reverse_lazy
from .models import Expense, Category
from .views import ExpenseListView, CategoryListView

urlpatterns = [
    path('expense/list/',
         ExpenseListView.as_view(),
         name='expense-list'),
    path('expense/create/',
         CreateView.as_view(
             model=Expense,
             fields='__all__',
             success_url=reverse_lazy('expenses:expense-list'),
             template_name='generic_update.html'
         ),
         name='expense-create'),
    path('expense/<int:pk>/edit/',
         UpdateView.as_view(
             model=Expense,
             fields='__all__',
             success_url=reverse_lazy('expenses:expense-list'),
             template_name='generic_update.html'
         ),
         name='expense-edit'),
    path('expense/<int:pk>/delete/',
         DeleteView.as_view(
             model=Expense,
             success_url=reverse_lazy('expenses:expense-list'),
             template_name='generic_delete.html'
         ),
         name='expense-delete'),

    path('category/list/',
         CategoryListView.as_view(),
         name='category-list'),
    path('category/create/',
         CreateView.as_view(
             model=Category,
             fields='__all__',
             success_url=reverse_lazy('expenses:category-list'),
             template_name='generic_update.html'
         ),
         name='category-create'),
    path('category/<int:pk>/delete/',
         DeleteView.as_view(
             model=Category,
             success_url=reverse_lazy('expenses:category-list'),
             template_name='generic_delete.html'
         ),
         name='category-delete'),
    path('category/<int:pk>/edit/',
         UpdateView.as_view(
             model=Category,
             fields='__all__',
             success_url=reverse_lazy('expenses:category-list'),
             template_name='generic_update.html'
         ),
         name='category-edit'),
]

project/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('',
         RedirectView.as_view(pattern_name='expenses:expense-list'),
         name='dashboard'),
    path('expenses/',
         include(('expenses.urls', 'expenses'), namespace='expenses')),
]

expenses/models.py
import datetime
from django.db import models


class Category(models.Model):
    class Meta:
        ordering = ('name',)

    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return f'{self.name}'


class Expense(models.Model):
    class Meta:
        ordering = ('-date', '-pk')

    category = models.ForeignKey(Category, models.PROTECT, null=True, blank=True)

    name = models.CharField(max_length=50)
    amount = models.DecimalField(max_digits=8, decimal_places=2)

    date = models.DateField(default=datetime.date.today, db_index=True)

    def __str__(self):
        return f'{self.date} {self.name} {self.amount}'

expenses/forms.py
from django import forms
from .models import Expense, Category


class ExpenseSearchForm(forms.ModelForm):
    fromDate = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    toDate = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    CHOICES = (
        ('asc', 'Date (oldest first)'),
        ('desc', 'Date (newest first)'),
    )
    sortByDate = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)

    class Meta:
        model = Expense
        fields = ('name', 'fromDate', 'toDate', 'categories', 'sortByDate')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].required = False
        self.fields['fromDate'].required = False
        self.fields['toDate'].required = False
        self.fields['categories'].required = False
        self.fields['sortByDate'].required = False

expenses/views.py
from django.db.models import Sum, Count
from django.db.models.functions import TruncMonth
from django.views.generic.list import ListView

from .forms import ExpenseSearchForm
from .models import Expense, Category
from .reports import summary_per_category


class ExpenseListView(ListView):
    model = Expense
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        queryset = object_list if object_list is not None else self.object_list

        form = ExpenseSearchForm(self.request.GET)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            fromDate = form.cleaned_data.get('fromDate')
            toDate = form.cleaned_data.get('toDate')
            categories = form.cleaned_data.get('categories')
            sortByDate = form.cleaned_data.get('sortByDate')

            if name:
                queryset = queryset.filter(name__icontains=name)
            if fromDate:
                queryset = queryset.filter(date__gte=fromDate)
            if toDate:
                queryset = queryset.filter(date__lte=toDate)
            if categories:
                queryset = queryset.filter(category__in=categories)
            if sortByDate == 'asc':
                queryset = queryset.order_by('date')
            if sortByDate == 'desc':
                queryset = queryset.order_by('-date')

        totalAmountSpent = round(queryset.aggregate(total=Sum('amount'))['total'] or 0, 2)

        expense_summary = queryset.annotate(month=TruncMonth('date')).values('month').annotate(
            total_spent=Sum('amount'))

        for expense in expense_summary:
            expense['total_spent'] = round(expense['total_spent'], 2)

        return super().get_context_data(
            form=form,
            object_list=queryset,
            summary_per_category=summary_per_category(queryset),
            totalAmountSpent=totalAmountSpent,
            expense_summary=expense_summary,
            **kwargs)


class CategoryListView(ListView):
    model = Category
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.annotate(num_expenses=Count('expense'))
        return queryset

expenses/templates/expenses/category_list.html
{% extends "base.html" %}

{% block content %}
    <a href="{% url 'expenses:category-create' %}">add</a>

    <table border="1">
        <thead>
        <tr>
            <th>name</th>
            <th>number of expenses</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for obj in object_list %}
            <tr>
                <td>
                    {{ obj.name }}
                </td>
                <td>
                    {{ obj.num_expenses }}
                </td>
                <td>
                    <a href="{% url 'expenses:category-edit' obj.id %}">edit</a>
                    <a href="{% url 'expenses:category-delete' obj.id %}">delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% include "_pagination.html" %}
{% endblock %}

expenses/templates/expenses/expense_list.html
{% extends "base.html" %}

{% block content %}

    <a href="{% url 'expenses:expense-create' %}">add</a>
    <hr>
    <table border="1">
        <caption>Seach filter</caption>
        <tr>
            <td>
                <form method="get" action="">
                    {{ form.as_p }}
                    <button type="submit">search</button>
                </form>
            </td>
        </tr>

    </table>

    <br>
    <hr>

    <table border="1">
        <caption>Expenses</caption>
        <thead>
        <tr>
            <th>no.</th>
            <th>category</th>
            <th>name</th>
            <th>amount</th>
            <th>date</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>

        {% for obj in object_list %}
            <tr>
                <td>{{ page_obj.start_index|add:forloop.counter0 }}.</td>
                <td>{{ obj.category|default:"-" }}</td>
                <td>{{ obj.name|default:"-" }}</td>
                <td>{{ obj.amount|floatformat:2 }}</td>
                <td>{{ obj.date }}</td>
                <td>
                    <a href="{% url 'expenses:expense-edit' obj.id %}">edit</a>
                    <a href="{% url 'expenses:expense-delete' obj.id %}">delete</a>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="5">no items</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% include "_pagination.html" %}
    <hr>
    <table border="1">
        <caption>Summary per category</caption>
        <tr>
            {% for category, total in summary_per_category.items %}
                <tr>
                    <td>{{ category }}:</td>
                    <td>{{ total|floatformat:2 }}</td>
                </tr>
            {% endfor %}
        </tr>
    </table>
    <hr>
    <table border="1">
        <caption>Total amount spent</caption>
        <tr>
            <td>{{ totalAmountSpent }}</td>
        </tr>
    </table>
    <br>
    <hr>
    <table border="1-">
        <caption>Summary per year-month</caption>
        <tr>
            <th>Year-Month</th>
            <th>Total Spent</th>
        </tr>
        {% for expense in expense_summary %}
            <tr>
                <td>{{ expense.month|date:"Y-m" }}</td>
                <td>{{ expense.total_spent }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

project/templates/_pagination.html
<div class="pagination">
    <span class="pagination__nav">
        {% load my_tags %}

        {% if is_paginated %}
            {% if page_obj.has_previous %}
                <a href="?{% param_replace page=1 %}">First</a>
                {% if page_obj.previous_page_number != 1 %}
                    <a href="?{% param_replace page=page_obj.previous_page_number %}">Previous</a>
                {% endif %}
            {% endif %}

            Page {{ page_obj.number }} of {{ paginator.num_pages }}

            {% if page_obj.has_next %}
                {% if page_obj.next_page_number != paginator.num_pages %}
                    <a href="?{% param_replace page=page_obj.next_page_number %}">Next</a>
                {% endif %}
                <a href="?{% param_replace page=paginator.num_pages %}">Last</a>
            {% endif %}

            <p>Objects {{ page_obj.start_index }}—{{ page_obj.end_index }}</p>
        {% endif %}
    </span>
</div>

project/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block meta_title %}Expenses app{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  </head>
  <body>
	<a href="{% url 'expenses:expense-list' %}">Expenses</a> | 
	<a href="{% url 'expenses:category-list' %}">Categories</a> | 
	<hr>
    {% block content %}{% endblock %}
  </body>
</html>

project/templates/generic_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Confirm removing "{{object}}"</h1>
<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">delete</button>
</form>

{% endblock %}

project/templates/generic_update.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">save</button>
</form>

{% endblock %}